import Head from "next/head";
import { Grid, Navbar, Text } from "@nextui-org/react";
import Program from "../components/program";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar variant="static" isCompact>
        <Navbar.Brand>
          <Text b color="inherit">
            Urograms
          </Text>
        </Navbar.Brand>
      </Navbar>
      <main>
        <Text size="$4xl">For Windows (x64)</Text>
        <Grid.Container>
          <Grid xs={4} css={{ p: "$3" }}>
            <Program
              logo="https://github.com/Oein/Urograms_static/raw/main/3dp_logo.png"
              name="3DP Chip"
              desc="드라이버를 손쉽게 다운받을 수 있어요"
              down="https://github.com/Oein/Urograms_static/raw/main/3dp.exe"
              site="3dpchip.com"
            />
          </Grid>
          <Grid xs={4} css={{ p: "$3" }}>
            <Program
              logo="https://github.com/Oein/Urograms_static/raw/main/fdm_logo.png"
              name="FDM"
              desc="빠르게 파일들을 다운받을 수 있어요"
              down="https://github.com/Oein/Urograms_static/raw/main/fdm.exe"
              site="freedownloadmanager.org"
            />
          </Grid>
          <Grid xs={4} css={{ p: "$3" }}>
            <Program
              logo="https://github.com/Oein/Urograms_static/raw/main/brave_logo.png"
              name="Brave"
              desc="광고없이 3배 빠르게 인터넷을 사용할 수 있어요"
              down="https://referrals.brave.com/latest/BraveBrowserSetup.exe"
              site="brave.com"
            />
          </Grid>
        </Grid.Container>
        <Text size="$3xl">For Windows Developers</Text>
        <Grid.Container>
          <Grid xs={4} css={{ p: "$3" }}>
            <Program
              logo="https://github.com/Oein/Urograms_static/raw/main/vsc_logo.png"
              name="Visual Studio Code"
              desc="모두를 위한 IDE에요"
              down="https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user"
              site="code.visualstudio.com"
            />
          </Grid>
          <Grid xs={4} css={{ p: "$3" }}>
            <Program
              logo="https://github.com/Oein/Urograms_static/raw/main/git_logo.png"
              name="Git (2.39.0)"
              desc="쉽게 버전을 관리 할 수 있어요"
              down="https://github.com/git-for-windows/git/releases/download/v2.39.0.windows.1/Git-2.39.0-64-bit.exe"
              site="git-scm.com"
            />
          </Grid>
        </Grid.Container>
      </main>
    </>
  );
}
